name: Create Diffend.io Links and Comment Text
on:
  pull_request:
    paths:
      - '**.gem'
permissions:
  contents: read

jobs:
  create_diffend_io_links_and_comment_text:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Create Diffend.io Links and Comment Text
        run: |
          ./create_diffend_io_links.rb -b $GITHUB_BASE_REF -s $GITHUB_SHA
          echo ${{ github.event.number }} > ./artifacts/pr_number.txt
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: comment_text_and_pr_number
          path: artifacts/
